version: '3.4'

services:
  api:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PedidosDB;User=sa;Password=Your_password123;TrustServerCertificate=true;Encrypt=False

    networks:
      - packing-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - packing-network

networks:
  packing-network:
    driver: bridge
